### ISSUE TITLE
Demo environment: An error occurs at SERVER2019-DE

### ISSUE THREAD

**Issue by marcelcremer** [0x101-Cyber-Security/NetLock-RMM-Web-Console#1]
Whenever the above server gets selected in Demo environment, the following error messages appear and the site becomes unusable. No network request is logged after the click:

![image](https://github.com/user-attachments/assets/b4e2e476-7a5e-47c7-b8d0-ae042077d6f9)

![image](https://github.com/user-attachments/assets/8091c91d-abf0-48b6-84c4-d87193c6e5d1)

**Comment by 0x100001** [comment]
@marcelcremer sorry for the late response and thanks for reporting. GitHub didnt send me a notifcation. The reason was a corrupted db entry caused by the backup system. It's already fixed. :)
